dist: bionic
language: go

services:
  - docker

go:
  - 1.15.x
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

go_import_path: github.com/percona/rds_exporter

env:
  global:
    # AWS - PMM Autotest account.
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWGCO72MJZ
    - secure: "X8jXCbsnCkyEsZN11AQ5NgF5Wl84ZTWxr8LuWXgVZ/3QwRvY7rK25FZVwf8TQqF3wch92WFnSwF9jQ37cz0H6SOa+tQ0NHDhUGIqEfdIlIfb8lGvEEPsD3OPenqRZWDRFFoywgkqu+PZU2uuFW5gC93RbClgBGv4oy+NrJF+Etkikv6E+mMZQc0O/UtEZUyXvRnfKY0/zPAHPsSNtEBvk3Q2lAIsl31pfMn6m1rBxPmuHShsigo+smMZTGXkijIa/aXUNOxz5lXppjvMmbNAg4/3+46MHTDXLmX7irGaUMvKKi4Ya6Hvu9+6UGjInrothVN98Y2k2J+ERZooM7ND7kv3vn3RilYbBhnpsdmmpL0nEQYTsJBvaaWKRZMIxS0Xd21CKOSGN+8Omq9iBgiW1L87xKxYD78OF+2Z9VwzHHk+Oaq2ky3LT/z3WGtnMWpURSxvjw76neFIxoIMHFVIZh0kywrmObZy3mgF0zzC/jRU2PK/ie9k0LJhxuHoEeb4b55f1PmUfhCJ7KblE3x13SlUUQqnvIL7qscKL1nEtFl/kidHtBYJAZzi0ctb2mHduzi89VYKqu6w3S93HpQQLkqpg9+i+i890mQrpytFGrcGVj4SikIE1fwlv/V8MS9zZukvizSV9l/Z0hV5YDqqHPX0UICrf7w/u9vkZSsz45g="
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "2OwS09wZF45Is+/fGsXrPXjzQ3pd1DgX6FC/bCoclK81L9Ad8ghGcNPMj4fScyaLHur6kEKPkurZgKoIhNzbLPArg1rna/BqJFIJFtmHIuTKRbyDvv2rU0hqvIaMWdHHDHXuFhpHtyiczzids/JzfurzHyoZZpl6mZ7MrFU2qoR9MH/pnYFdXAf1D6Af0qHWC6SC/jCln1knhP1eYnVYvA4ImYa+uLXcPC6pPO/LuRzrRw79BamMfH4RmCI27abUVp/Vwim36Fxxt9fiXkCImPnK4PALqTpGhcBdgp/fHmqnBHSlfVKFREmwpmtQ4EGlMau1WgSUlqH89GRQ5gvXv/J8wwQRLZQRUalM34v9t/XjbWbTg+5LwJNbtI229RsY7XS0Ty0UnLSmb4GeiUZ1mf1sKgnTAZM/bz6np3hCk8d0dJlaJMO+9HL/4O2wTNFmRLsYbWAwhrS3Jhk6eQ9XnS+OPod4qVF1LjvCeM9WPUG1p7SyTrtzaTi0z/elaQ60GzZ6VCto3hXHTqhtEuZFIMxqxgUxDIAqppudE7jzZaU6DNscEyjmKnh+cKsTzq1bAdBA2wK0cnR8aemZJKZqEcyGwZPs185PyVKhZ53s7362hKD4th4td2V4rNqJ/R+qGE57KRKUBmELWPPCSh7YvdaixTaT1QM9rzZjtWhUBMg="

install:
  # install reviewdog and golangci-lint
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

script:
  - make travis
